// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sonvert.App.Data;

#nullable disable

namespace Sonvert.App.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824015742_AddGlossaryEntries")]
    partial class AddGlossaryEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Sonvert.App.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Sonvert.App.Models.CharacterEmotionClip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emotion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PromptText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativeAudioPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterEmotionClips");
                });

            modelBuilder.Entity("Sonvert.App.Models.GlossaryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTerm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetTerm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GlossaryEntries");
                });

            modelBuilder.Entity("Sonvert.App.Models.HistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emotion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceAudioRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedAudioRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TranslatedText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("HistoryEntries");
                });

            modelBuilder.Entity("Sonvert.App.Models.CharacterEmotionClip", b =>
                {
                    b.HasOne("Sonvert.App.Models.Character", "Character")
                        .WithMany("EmotionClips")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Sonvert.App.Models.Character", b =>
                {
                    b.Navigation("EmotionClips");
                });
#pragma warning restore 612, 618
        }
    }
}
